# Generated by Django 2.0.6 on 2018-06-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20180619_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmer',
            old_name='language',
            new_name='languages',
        ),
    ]
